// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgpvbyxyrdculwzjjltg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNncHZieXh5cmRjdWx3empqbHRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDEzNjQsImV4cCI6MjA2NzExNzM2NH0.4lBv-Upof2_OChPO62tpKCisKsMDMziacWxJc08Lyts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});